In [19]:
# 라이브러리 사용

import tensorflow as tf
import pandas as pd

In [20]:
# 1. 과거의 데이터 준비

파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [21]:
# 원핫인코딩

인코딩 = pd.get_dummies(아이리스)
인코딩.head()

# 종속변수가 범주형(양적 X)
# pd.get_dummies() -> 자료들 중 범주형인 것들만 골라 1, 0으로 바꿔주는 코드

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [22]:
# 칼럼이름 출력
print(인코딩.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [23]:
# 독립변수, 종속변수

독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor',
       '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [24]:
# 2.모델의 구조 만들기

X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation = 'softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

# 분류모델 - sigmoid, softmax 차이 알아보기
# y의 최대값 1, 최소값 0 -> y=softmax(w1x1+w2x2+..+b)로 감싸주면 됨
# activation: 활성화 함수
# 분류에 사용하는 loss - crossentropy, 회귀에 사용하는 loss - mse
# metrics='accuracy' -> 정확도도 함께 볼 수 있음

In [25]:
# 모델 구조 확인
model.summary()

Model: "functional_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_12 (Dense)             (None, 8)                 40        
_________________________________________________________________
dense_13 (Dense)             (None, 8)                 72        
_________________________________________________________________
dense_14 (Dense)             (None, 8)                 72        
_________________________________________________________________
dense_15 (Dense)             (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [26]:
# 3. 데이터로 모델 학습(FIT)시키기

model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 762us/step - loss: 1.3393 - accuracy: 0.3333
Epoch 2/100
5/5 [==============================] - 0s 713us/step - loss: 1.1579 - accuracy: 0.3333
Epoch 3/100
5/5 [==============================] - 0s 730us/step - loss: 1.0839 - accuracy: 0.3667
Epoch 4/100
5/5 [==============================] - 0s 598us/step - loss: 1.0462 - accuracy: 0.5733
Epoch 5/100
5/5 [==============================] - 0s 568us/step - loss: 1.0205 - accuracy: 0.3733
Epoch 6/100
5/5 [==============================] - 0s 585us/step - loss: 1.0037 - accuracy: 0.3533
Epoch 7/100
5/5 [==============================] - 0s 571us/step - loss: 0.9875 - accuracy: 0.3333
Epoch 8/100
5/5 [==============================] - 0s 591us/step - loss: 0.9704 - accuracy: 0.3400
Epoch 9/100
5/5 [==============================] - 0s 559us/step - loss: 0.9545 - accuracy: 0.3333
Epoch 10/100
5/5 [==============================] - 0s 600us/step - loss: 0.9407 - accuracy: 0.3400
Epoch 11/

5/5 [==============================] - 0s 707us/step - loss: 0.1424 - accuracy: 0.9600
Epoch 84/100
5/5 [==============================] - 0s 626us/step - loss: 0.1382 - accuracy: 0.9667
Epoch 85/100
5/5 [==============================] - 0s 614us/step - loss: 0.1359 - accuracy: 0.9667
Epoch 86/100
5/5 [==============================] - 0s 603us/step - loss: 0.1372 - accuracy: 0.9600
Epoch 87/100
5/5 [==============================] - 0s 610us/step - loss: 0.1280 - accuracy: 0.9733
Epoch 88/100
5/5 [==============================] - 0s 640us/step - loss: 0.1382 - accuracy: 0.9667
Epoch 89/100
5/5 [==============================] - 0s 602us/step - loss: 0.1274 - accuracy: 0.9600
Epoch 90/100
5/5 [==============================] - 0s 605us/step - loss: 0.1268 - accuracy: 0.9733
Epoch 91/100
5/5 [==============================] - 0s 596us/step - loss: 0.1187 - accuracy: 0.9667
Epoch 92/100
5/5 [==============================] - 0s 629us/step - loss: 0.1257 - accuracy: 0.9600
Epoch 93/100


In [27]:
# 4. 모델 이용하기

#맨 처음 데이터 5개
print(model.predict(독립[:5]))
print(종속[:5])

#맨 마지막 데이터 5개
print(model.predict(독립[-5:]))
print(종속[-5:])


[[9.9946374e-01 5.3624390e-04 2.4448004e-09]
 [9.9801123e-01 1.9887735e-03 1.8156291e-08]
 [9.9901617e-01 9.8385650e-04 1.0427268e-08]
 [9.9778724e-01 2.2126914e-03 3.5088554e-08]
 [9.9955016e-01 4.4981038e-04 2.2946955e-09]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
[[6.3961721e-05 1.9126756e-01 8.0866849e-01]
 [4.9961494e-05 1.2108235e-01 8.7886763e-01]
 [8.1531216e-05 2.0383382e-01 7.9608464e-01]
 [7.4902666e-05 1.2970699e-01 8.7021804e-01]
 [1.2620576e-04 1.7102312e-01 8.2885069e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [28]:
# 학습한 가중치(weights) 출력

model.get_weights()

[array([[ 0.48354208,  0.7504801 ,  0.31478086,  0.36884785,  0.08138817,
          0.5675977 ,  0.08023102,  0.40541407],
        [-0.47280687,  0.5328922 ,  0.501298  , -0.61695004, -0.6025233 ,
          0.0876625 ,  0.7965477 , -0.4726795 ],
        [ 0.39271408, -0.2945861 , -0.7219694 , -0.77016306, -0.05798047,
          0.21033409, -0.49135074, -0.12167181],
        [ 0.25267884,  0.2744501 ,  0.2781905 , -0.68420327, -0.6680038 ,
          0.64031476, -0.01015977, -0.15199931]], dtype=float32),
 array([ 0.23294319,  0.10775524,  0.13289136, -0.07423621,  0.12294208,
        -0.06240577,  0.1849169 ,  0.08605705], dtype=float32),
 array([[-0.37613627,  0.24510096,  0.63427246,  0.5469135 ,  0.46230257,
         -0.44279414,  0.13768141,  0.14703353],
        [-0.08137362,  0.387053  , -0.16528916,  0.81078976,  0.562097  ,
         -0.11900248,  0.34900653, -0.20846322],
        [ 0.45747536,  0.5012583 , -0.86230785,  0.11048368, -0.54587674,
          0.07123871,  0.26426703,